[package]
name = "cloudflare-ddns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cloudflare = "0.10.1"
reqwest = "0.11.14"
serde = "1.0.152"
thiserror = "1.0.38"
